Respect .eslintignore
kentcdodds/prettier-eslint-atom pull request #15
Opened 2017-01-28 09:26 UTC by robwise

2017-01-28 21:09 UTC, kentcdodds requested changes
Other than one little thing I think this is great!

2017-01-28 21:09 UTC, kentcdodds commented on package.json
> +      "description": "Don't format on save if the file is ignored by your ``.eslintignore`. Note: 'Format on Save' must be enabled for this to have effect.",
You've got two backticks here (and it's showing in the screenshot) :)

2017-01-29 05:39 UTC, kentcdodds approved these changes

2017-01-29 05:41 UTC, merged

2017-01-29 11:18 UTC, robwise commented on package.json
> +      "description": "Don't format on save if the file is ignored by your ``.eslintignore`. Note: 'Format on Save' must be enabled for this to have effect.",
woops!